### ISSUE TITLE
[BUG] Error whilst trying to build

### ISSUE THREAD

**Issue by MagicLike** [SanjaySunil/stackedit-desktop#106]
#### How major is the bug from 1 - 10

- Scale: 5

#### What type of bug is it?

- Type: Build Error

#### System Information

- OS: Windows 10 Pro

#### Steps required to reproduce the bug

Steps:
- Clone Code
- `npm run build`

#### Screenshot (In most cases required)

- Screenshot:
![grafik](https://user-images.githubusercontent.com/82117109/164717424-c8eb2a83-b1c6-4c14-9d8f-1e6556b6e303.png)

#### Additional Information
When building only for Windows (`npm run win:build`) there is no error and it works.

**Comment by SanjaySunil** [comment]
Instead of `npm run build`, you need to run `npm run dist`.

See `package.json`.
